# Generated by Django 4.2.3 on 2023-07-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_testdb_desc_testdb_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testdb",
            name="desc",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="testdb",
            name="tags",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
