# Generated by Django 4.2.3 on 2023-07-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_testdb_desc_alter_testdb_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdb",
            name="t",
            field=models.BooleanField(null=True),
        ),
    ]
