# Generated by Django 4.2.3 on 2023-07-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_testdb_t"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("ordering", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("desc", models.TextField(null=True)),
                ("set", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "project_id",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="TunePad Project ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default=None,
                        max_length=512,
                        null=True,
                        verbose_name="External URL",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Markdown Text",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
