# Generated by Django 4.2.3 on 2023-07-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_playlistnode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlistnode",
            name="set",
        ),
    ]
