# Generated by Django 4.2.3 on 2023-07-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_playlistnode_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistnode",
            name="type",
            field=models.CharField(default="/g/", max_length=3),
        ),
    ]
