# Generated by Django 4.2.3 on 2023-08-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_playlistnode_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistnode",
            name="project_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=15,
                null=True,
                verbose_name="TunePad Project ID",
            ),
        ),
    ]
