# Generated by Django 4.2.3 on 2023-08-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_playlistnode_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistnode",
            name="project_id",
            field=models.CharField(
                blank=True,
                default="1200",
                max_length=15,
                null=True,
                verbose_name="TunePad Project ID",
            ),
        ),
    ]
